version: '3'
services:
  angular-app:
    build:
      context: ./../centrica-client
      dockerfile: Dockerfile
    ports:
      - 4200:80
    depends_on:
      - dotnet-app
  dotnet-app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - sql-server
  
  sql-server:
    build:
      context: ./../centrica-database
      dockerfile: Dockerfile
    ports:
      - 1433:1433

