version: '3'
services:
  #sql-server:
  #  build:
  #    context: ./../centrica-database
  #    dockerfile: Dockerfile
  #  environment:
  #    - MSSQL_SA_PASSWORD=P@ssw0rd
  #  ports:
  #    - 1433:1433

  angular-app:
    build:
      context: ./../centrica-client
      dockerfile: Dockerfile
    ports:
      - 4200:80

  dotnet-app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 80:5057